steps:
  - name: 'gcr.io/k8s-skaffold/skaffold'
    id: 'Build artifact'
    args:
      - 'skaffold'
      - 'build'
      - '--interactive=false'
      - '--file-output=/workspace/artifacts.json'

  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    id: 'Create release'
    entrypoint: gcloud
    args:
      [
        'deploy', 'releases', 'create', 'rel-${SHORT_SHA}',
        '--delivery-pipeline', 'kafka-2-pubsub',
        '--region', 'us-central1',
        '--build-artifacts', '/workspace/artifacts.json'
      ]

options:
  logging: CLOUD_LOGGING_ONLY
